### ISSUE TITLE
add route53 + domain name for nessus

### ISSUE THREAD

**Issue by alice-carr** [alphagov/cyber-security-nessus#13]
We should get a domain name for nessus rather than accessing it via the (always changing) ip

**Comment by akinnane** [comment]
There are examples of how to do this in https://github.com/alphagov/cyber-security-splunk/tree/master/terraform/modules/splunk-hybrid-searchhead acm.tf,rouet53.tf, alb.tf

**Comment by denizgenc** [comment]
Just want to make sure - is the 6762... account OK for testing? I'd like to run some terraform to test the ALB stuff I've adapted for Nessus, but I'm afraid of breaking something in use. @pritchyspritch opinions?

**Comment by pritchyspritch** [comment]
I think I'd prefer if you did it in the testing account just because I am working on it atm and if it breaks I will be blocked. The pipeline will be running fairly regularly and will be messing up whatever you have as well probably

**Comment by denizgenc** [comment]
Which account do you mean by the testing account? 489...?

**Comment by pritchyspritch** [comment]
Testing is the 103... account, but it doesn't really matter which one

**Comment by denizgenc** [comment]
https://github.com/alphagov/cyber-security-nessus/pull/21#issuecomment-624695529
