### ISSUE TITLE
Click ops Nessus server.

### ISSUE THREAD

**Issue by 0atman** [alphagov/cyber-security-nessus#2]
Spin up a nessus server using the prebuilt AMI and configure it to send data to Splunk. Document anything noteworthy for later automation steps

**Comment by pritchyspritch** [comment]
- Nessus BYOL AMI added to vuln testing account
- Installed professional
- Created login and added all creds to param store in same account

**Comment by alice-carr** [comment]
Started forwarding the nessus logs to cloudwatch and then to splunk (with csls) however this was taking a long time to go through (around an hour for one file) and also cloudwatch has a limit on the amount of data you can send to it at once. May be best to set up a splunk heavy forwarder on an ec2 and send straight to splunk

**Comment by denizgenc** [comment]
As Alice said, the logs _are_ being forwarded at the moment, so I'm closing this to allow for work on Terraform etc to go forward
