### ISSUE TITLE
Create Terraform to deploy Nessus

### ISSUE THREAD

**Issue by pritchyspritch** [alphagov/cyber-security-nessus#3]
Once we have clickops'd Nessus, we should write some terraform that automates the process

**Comment by alice-carr** [comment]
A few things to consider with this terraform:

- [ ] how do we get the scans onto the nessus instance
- [ ] how do we supply the access key and secret key to the instance (needs to be generated per instance)
- [ ] how do we get the user_id

**Comment by alice-carr** [comment]
Having trouble generating access key and secret key programmatically. Have tested passing the session token through to the scan api as well but this does not work.

**Comment by alice-carr** [comment]
**Creating scans**
Scans need to be created before being run. We would ideally create a scan in the start up script where we create a user. 
However, [according to this](https://community.tenable.com/s/article/The-differences-between-Nessus-6-and-Nessus-7) "The ability to manage scans via API and CLI has been removed in v7. All Nessus Pro scanning operations must be done through the user interface."

**Comment by denizgenc** [comment]
I think that at this point, we should contact Nessus for official support.

Our main issue is: "How do we programmatically generate an `accessKey` and `secretKey` when we don't know what the `user_id` is?"

Maybe that can be broken down further:
- How do we programmatically find out the `userid`, given a username?
- How do we programmatically generate an `accessKey` given that `user_id`?

**Comment by denizgenc** [comment]
So we're unsure of what email we used to open a support account with, considering that “Email requests must be sent from one of the email addresses provided to Tenable as an authorized Support contact.” (see https://www.tenable.com/products/nessus/nessus-faq#Nessus_Support ).

Another complication is that there's a whole procurement chain that needs to be resolved (engineering -> head of cyber -> GDS procurement -> some third party -> Nessus).

So for now we're blocked on doing things programmatically, so we'll take a two-pronged approach:

- Contact the head of cyber to figure out what our Nessus support email is (I'll do this bit), and maintain contact with Nessus to figure out how to do things programmatically using the API
- Finish off all the Terraform, and then write documentation for the steps that have to be done manually (e.g. setting up scans).

**Comment by denizgenc** [comment]
We were able to generate an API key programmatically!

OK, it turns out that we can generate a session token by making a POST request to the `/session` endpoint using the Nessus username and password, and then make a PUT request to the `/session/keys` endpoint, using the token:

```python
session_url = "/session"
params = {
    "username": nessus_username,
    "password": nessus_password
}
response = requests.post(nessus_url + session_url, data=params, verify=False)
response_token = json.loads(response.text)
headers = {"X-Cookie": f"token={response_token['token']}"}

# get api keys
keys_url = "/session/keys"
keys_response = requests.put(nessus_url + keys_url, headers=headers, verify=False)
keys = json.loads(keys_response.text)
access_key = keys['accessKey']
secret_key = keys['secretKey']
```

**Comment by alice-carr** [comment]
According to the docs api keys are persistent and do not time out - we can therefore store them in SSM. WIll probably be easiest to do this in a concourse pipeline that takes the following steps:
- builds the nesses ec2 terraform
- runs a script that assumes a role and generates the api tokens (on docker maybe?)
- puts those keys in SSM
- runs the terraform to create the lambda and adds that tokens as env vars from ssm
