### ISSUE TITLE
fix TODOs in Readme

### ISSUE THREAD

**Issue by alice-carr** [alphagov/cyber-security-nessus#30]
When the readme was first created, there was some information that was not available to complete it. These were left as TODOs and should be replaced when we can. These are:

- the index name for splunk
- the link to the api  docs (which are hosted on the instance - as we currently have no hostename for the nessus instance they must at the moment be accessed by the changing ip address)

**Comment by denizgenc** [comment]
We have got a hostname for it now, though, so I can add that at least. I'll need to look at the source/ask around for the Splunk index, though.
